schema_version: 1

context:
  version: "0.6.4"

package:
  name: libfreenect
  version: ${{ version }}

source:
  url: https://github.com/OpenKinect/libfreenect/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 6169600f999729a7f99dd71a9825ed6e7aec8b8aac4f532ecf2911f76133c125

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake <=3.12.4
    - ninja
  host:
    - libusb >=1.0.18
  run:
    - libusb >=1.0.18

tests:
  - script:
      - if: unix
        then:
          - test -f $PREFIX/lib/libfreenect${SHLIB_EXT}
          - test -f $PREFIX/include/libfreenect/libfreenect.h
      - if: win
        then:
          - if exist %LIBRARY_LIB%\\freenect.lib (exit 0) else (exit 1)
          - if exist %LIBRARY_INC%\\libfreenect\\libfreenect.h (exit 0) else (exit 1)

about:
  homepage: https://openkinect.org
  repository: https://github.com/OpenKinect/libfreenect
  license: Apache-2.0 OR GPL-2.0-only
  license_file: APACHE20
  summary: Userspace driver for the Microsoft Kinect
  description: |
    libfreenect is a userspace driver for the Microsoft Kinect.
    It supports RGB and depth image streams, motors, accelerometer,
    LED, and audio on Linux, macOS, and Windows.

extra:
  recipe-maintainers:
    - cornerfarmer