schema_version: 1

context:
  name: ids-peak
  version: "26.06.1"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  path: ./ids-peak_${{ version }}_amd64.tar.gz
  sha256: ebf5db7dabde954e1ea1a4c5e6f25e6e2ae539067fddd8481cb1f2e2165f02dc

build:
  number: 1
  script: |
    #cp lib/x86_64-linux-gnu/* lib/ -r
    #rm -r lib/x86_64-linux-gnu
    cp * $PREFIX/ -r

    # Create activation/deactivation scripts
    mkdir -p $PREFIX/etc/conda/activate.d
    mkdir -p $PREFIX/etc/conda/deactivate.d

    cat > $PREFIX/etc/conda/activate.d/${{ name }}-env.sh << 'EOF'
    export GENICAM_GENTL64_PATH=$CONDA_PREFIX/lib/x86_64-linux-gnu/ids-peak/cti
    EOF

    cat > $PREFIX/etc/conda/deactivate.d/${{ name }}-env.sh << 'EOF'
    unset GENICAM_GENTL64_PATH
    EOF
  skip:
    - win

requirements:
  run:
    - qt-main 5.*
    - libusb
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x.x') }}


tests:
  - script:
    - ids_ipconfig --version

about:
  homepage: https://de.ids-imaging.com/ids-peak.html
  documentation: https://de.ids-imaging.com/ids-peak.html

extra:
  recipe-maintainers:
    - cornerfarmer
